// Context sentences for all 313 dictionary words (Dolch service words + nouns).
// Every sentence: capitalized, period-terminated, contains the target word
// (not first/last token unless in EDGE_EXCEPTIONS), and built only from the
// 313-word vocabulary (plus simple inflections, or EXTRA_FORMS for legitimate
// dictionary-word inflections). Declarative statements only (no questions).
export const SENTENCES = {
  a: 'We can see a bird.',
  and: 'I like cake and milk.',
  away: 'The cat ran away fast.',
  big: 'She has a big dog.',
  blue: 'I have a blue ball.',
  can: 'You can play with me.',
  come: 'Please come here now.',
  down: 'We sat down to eat.',
  find: 'Help me find my toy.',
  for: 'This cake is for you.',
  funny: 'That funny pig can jump.',
  go: 'We will go to school.',
  help: 'You can help my sister.',
  here: 'Come here and play with us.',
  i: 'Look, I can jump up and down.',
  in: 'The fish are in the water.',
  is: 'This is my new game today.',
  it: 'We will make it today.',
  jump: 'The little dog can jump far.',
  little: 'A little bird sat there.',
  look: 'Please look at this picture.',
  make: 'Let us make a cake.',
  me: 'Please give me the toy.',
  my: 'I found my little shoe.',
  not: 'This is not my coat.',
  one: 'She has one red apple.',
  play: 'We will play in the garden.',
  red: 'I want a red apple.',
  run: 'The dog will run fast.',
  said: 'She said thank you today.',
  see: 'Look, we can see the tree.',
  the: 'We went to the farm.',
  three: 'I have three little birds.',
  to: 'We want to go home.',
  two: 'She has two brothers.',
  up: 'The sun will come up soon.',
  we: 'Now we can play together.',
  where: 'This is where you live.',
  yellow: 'The sun is yellow and warm.',
  you: 'Thank you for the cake.',
  all: 'We all like to sing.',
  am: 'I am going home now.',
  are: 'We are very good today.',
  at: 'The dog sat at the door.',
  ate: 'The boy ate an apple.',
  be: 'Please be good at school.',
  black: 'I saw a black cat.',
  brown: 'The brown horse can run.',
  but: 'I like cake but not milk.',
  came: 'A robin came to the nest.',
  did: 'She did want to make a cake.',
  do: 'We do want to go now.',
  eat: 'We eat bread every morning.',
  four: 'She has four little ducks.',
  get: 'Please get my red shoe.',
  good: 'That was a good game.',
  have: 'I have a new toy.',
  he: 'She said he can ride well.',
  into: 'The duck ran into the water.',
  like: 'I like to sing songs.',
  must: 'You must clean your coat.',
  new: 'She got a new doll.',
  no: 'There is no rain today.',
  now: 'Right now we must go home.',
  on: 'The cat sat on a chair.',
  our: 'This is our little house.',
  out: 'The dog went out to play.',
  please: 'She said please and thank you.',
  pretty: 'That is a pretty flower.',
  ran: 'The boy ran to school.',
  ride: 'We can ride the horse today.',
  saw: 'I saw a squirrel today.',
  say: 'She will say it to you.',
  she: 'My sister said she likes it.',
  so: 'He was so good today.',
  soon: 'We will soon eat some cake.',
  that: 'I like that little song.',
  there: 'A bird was sitting there today.',
  they: 'She said they went to the farm.',
  this: 'We like this good cake.',
  too: 'I want cake too, and milk.',
  under: 'The kitty sat under the table.',
  want: 'I want some milk now.',
  was: 'It was a funny game.',
  well: 'She sings very well today.',
  went: 'We went to the garden.',
  what: 'She found what she wanted.',
  white: 'I saw a white rabbit.',
  who: 'I know who will help me now.',
  will: 'She will come home soon.',
  with: 'I will play with you.',
  yes: 'She said yes to the game.',
  after: 'We ran after the little dog.',
  again: 'She will play this song again soon.',
  an: 'She saw an old red boat.',
  any: 'We do not have any milk.',
  ask: 'I will ask my father now.',
  by: 'The cat sat by the door.',
  could: 'He could not find his shoe.',
  every: 'We play every day at school.',
  fly: 'Little birds fly over the tree.',
  from: 'She came from her big house.',
  give: 'Please give me the red ball.',
  going: 'We are going to the farm.',
  had: 'The girl had a new doll.',
  has: 'My brother has a yellow toy.',
  her: 'I will help her find it.',
  him: 'We gave him a warm coat.',
  his: 'He put his shoe by the door.',
  how: 'Look how fast the horse can run.',
  just: 'She just found her little kitty.',
  know: 'I know where the cow went.',
  let: 'Please let me help you today.',
  live: 'The rabbit and duck live here.',
  may: 'You may play in the garden.',
  of: 'We ate all of the bread.',
  old: 'This old house has a big door.',
  once: 'We saw a squirrel once at the farm.',
  open: 'Please open the door for me.',
  over: 'The boy jumped over the hill.',
  put: 'She will put the toy down.',
  round: 'This little ball is round and red.',
  some: 'We ate some corn at the party.',
  stop: 'Please stop and look at the sun.',
  take: 'I will take my toy home.',
  thank: 'We thank you for the cake.',
  them: 'I will give them some water.',
  then: 'She ate corn, then went to play.',
  think: 'I think the fish is little.',
  walk: 'We walk to school every morning.',
  were: 'They were good at the party.',
  when: 'This is when the sun goes down.',
  always: 'Our dog is always very good.',
  around: 'The children ran around the garden.',
  because: 'She was good because she got a toy.',
  been: 'We have been to the farm today.',
  before: 'Wash your hands before you eat.',
  best: 'This is the best cake we made.',
  both: 'We both like to sing songs.',
  buy: 'We will buy eggs at the farm.',
  call: 'Please call the dog to come home.',
  cold: 'The cold snow came down all morning.',
  does: 'She does like her new toy.',
  dont: 'She said I dont want to go.',
  fast: 'The fast horse can run well.',
  first: 'He was first to see the bird.',
  five: 'I have five apples in a box.',
  found: 'The boy found a little bird.',
  gave: 'Father gave me a new toy.',
  goes: 'She goes to school with her sister.',
  green: 'I like the green grass in our garden.',
  its: 'The bird sat in its nest.',
  made: 'Mother made a cake today.',
  many: 'We saw many sheep on the farm.',
  off: 'The cat jumped off the chair.',
  or: 'We will eat corn or bread.',
  pull: 'Help me pull this box home.',
  read: 'We read about a little duck.',
  right: 'Put the box right by the door.',
  sing: 'The children sing a good song.',
  sit: 'Come sit with me at the table.',
  sleep: 'The baby will sleep in her bed.',
  tell: 'Please tell me about your day.',
  their: 'The boys found their new ball.',
  these: 'We like these pretty yellow flowers.',
  those: 'Look at those birds in the tree.',
  upon: 'A bird sat upon the nest.',
  us: 'Come and play with us today.',
  use: 'We use water to wash our hands.',
  very: 'He can run very fast at school.',
  wash: 'Please wash your hands before you eat.',
  which: 'I know which toy she wants.',
  why: 'This is why she is so good.',
  wish: 'I wish for a new toy.',
  work: 'Father goes to work every morning.',
  would: 'She would like some warm milk.',
  write: 'Please write your name on the paper.',
  your: 'Put your shoe by the door.',
  about: 'Please tell me about your day.',
  better: 'This cake is better today.',
  bring: 'Please bring your toy here.',
  carry: 'I can carry the box.',
  clean: 'The clean coat is on the chair.',
  cut: 'She will cut the bread.',
  done: 'He has done his work.',
  draw: 'Let us draw a bird.',
  drink: 'You can drink the milk.',
  eight: 'I have eight red apples.',
  fall: 'The rain will fall in the garden.',
  far: 'The farm is not far away.',
  full: 'This full box has many toys.',
  got: 'We got a new kitty.',
  grow: 'Flowers grow in our garden.',
  hold: 'Please hold my hand now.',
  hot: 'This hot corn is good to eat.',
  hurt: 'She did hurt her feet at play.',
  if: 'Ask if you want some cake.',
  keep: 'You may keep the doll.',
  kind: 'This kind girl helps her father.',
  laugh: 'We laugh at the funny dog.',
  light: 'She will light the paper for us.',
  long: 'That is a long street.',
  much: 'Thank you very much today.',
  myself: 'I made myself a little cake.',
  never: 'I will never run away.',
  only: 'She has only one apple.',
  own: 'He has his own chair.',
  pick: 'Let us pick some corn.',
  seven: 'We saw seven little ducks.',
  shall: 'We shall go to school.',
  show: 'Please show me your picture.',
  six: 'The farmer has six cows.',
  small: 'This small kitty likes to play.',
  start: 'We will start the game.',
  ten: 'She has ten little ducks.',
  today: 'She said today is a good day.',
  together: 'We can play together now.',
  try: 'Please try to eat some corn.',
  warm: 'I like this warm bread.',
  apple: 'She ate a red apple with milk.',
  baby: 'The baby likes to laugh.',
  back: 'Come back to the house.',
  ball: 'This ball is red and round.',
  bear: 'A brown bear sat down.',
  bed: 'She put her doll on the bed now.',
  bell: 'This bell rings very well.',
  bird: 'A little bird can fly.',
  birthday: 'Today is my birthday party.',
  boat: 'The old boat goes fast.',
  box: 'This small box has a red toy.',
  boy: 'The boy likes to run.',
  bread: 'Father cut the bread for us.',
  brother: 'My brother can carry it.',
  cake: 'We will eat cake today.',
  car: 'This car is red and fast.',
  cat: 'The cat sat on the chair.',
  chair: 'She will sit on the chair now.',
  chicken: 'The chicken is in the garden.',
  children: 'The children like to play.',
  christmas: 'This Christmas we got new toys.',
  coat: 'Put your coat on before school.',
  corn: 'The farmer will pick some corn soon.',
  cow: 'The cow is on the farm.',
  day: 'It is a warm day today.',
  dog: 'The dog ran to me.',
  doll: 'My sister got a new doll for Christmas.',
  door: 'Open the door for me.',
  duck: 'The little duck ran to the farm.',
  egg: 'We ate an egg today.',
  eye: 'She has one blue eye open.',
  farm: 'This farm has many cows.',
  farmer: 'The farmer will help his cow.',
  father: 'My father can carry it.',
  feet: 'Wash your feet before bed.',
  fire: 'The fire keeps us warm.',
  fish: 'The little fish live in water.',
  floor: 'We sit on the clean floor to play.',
  flower: 'She gave her mother a pretty flower today.',
  game: 'We will play this game together.',
  garden: 'This garden has pretty flowers.',
  girl: 'The girl can sing well.',
  grass: 'This grass is green and long.',
  ground: 'On the warm ground we sat down.',
  hand: 'Take my hand and go.',
  head: 'Put your head down and sleep.',
  hill: 'We saw a hill by the farm.',
  home: 'We go home after school.',
  horse: 'The little horse can run.',
  house: 'This big house has a red door.',
  kitty: 'The kitty likes warm milk.',
  leg: 'He hurt his leg at play.',
  letter: 'She got a letter today.',
  man: 'The old man can sing.',
  men: 'Two men came to help.',
  milk: 'Please drink your milk now.',
  money: 'He put money in a box.',
  morning: 'This morning we ate eggs.',
  mother: 'My mother made a cake.',
  name: 'She will write her name on paper.',
  nest: 'Look, the nest has a little egg.',
  night: 'We sleep at night now.',
  paper: 'This paper has a pretty picture.',
  party: 'At the party we ate cake and corn.',
  picture: 'Look at this picture of my dog.',
  pig: 'The pig ran to the farm.',
  rabbit: 'A rabbit sat in the grass.',
  rain: 'The rain came down all morning.',
  ring: 'Mother has a pretty ring on her hand.',
  robin: 'A robin sat by the nest.',
  school: 'We walk to school today.',
  seed: 'Father put a seed in the ground.',
  sheep: 'The sheep ran to the hill.',
  shoe: 'Get your shoe and coat for school.',
  sister: 'My sister can read well.',
  snow: 'We saw snow fall on the hill.',
  song: 'This little song makes us laugh.',
  squirrel: 'A squirrel ran up the tree.',
  stick: 'The dog will carry a stick home.',
  street: 'Down this street we saw a cow.',
  sun: 'Today the sun came up over the hill.',
  table: 'Put the cake on the table now.',
  thing: 'That funny thing made us laugh.',
  time: 'It is time to eat.',
  top: 'On top of the hill we sat.',
  toy: 'He gave his toy to the baby.',
  tree: 'The tree by our house is old.',
  watch: 'Father will watch the game with us.',
  water: 'We drink water before we eat.',
  way: 'This is the way home.',
  wind: 'A cold wind came down the hill.',
  window: 'A bird sat by the window to sing.',
  wood: 'Father will cut this wood for the fire.',
  as: 'She is as good as her brother.',
};
export const EDGE_EXCEPTIONS = [];
export const EXTRA_FORMS = ['sat'];
